version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: development.Dockerfile
    environment: 
      - NODE_ENV=development
      - BOT_TOKEN=${BOT_TOKEN}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - WEBHOOK_PORT=${WEBHOOK_PORT}
      - WEBHOOK_PATH=${WEBHOOK_PATH}
      - IS_WEBHOOK_DISABLED=true
      - IMAGINARY_HOST=imaginary
      - IMAGINARY_API_KEY=imaginary_secret_api_key
    volumes:
      - ./src:/app/src

  imaginary:
    image: h2non/imaginary:latest
    environment:
       PORT: 80
    command: -key imaginary_secret_api_key